services:
  - type: web
    name: blog_dj
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn blog.wsgi"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
